### PR TITLE
Make sure the MacCatalyst app's binary is executable

### PR DESCRIPTION
**Pull request by premun**
I found this problem when trying to run a runtime-built app on Helix

### CODE REVIEW

**Review by akoeplinger — APPROVED** [review]

**Comment by akoeplinger** [comment]
I guess this is because we package the .app in a .zip for Helix upload and that doesn't preserve the executable bit?

**Comment by premun** [comment]
> I guess this is because we package the .app in a .zip for Helix upload and that doesn't preserve the executable bit?

Yeah, I did `tar -czvf` myself and maybe did something worng there. I was wondering if it's the XHarness' responsibility to make sure it is executable first but maybe it makes sense to just do it?

**Comment by akoeplinger** [comment]
Hmm if we're using a `tar.gz` then that should preserve the executable bit, I'm only aware of problems when using .zip.

It's probably harmless to just always run the `chmod` but it could point to some other infra issue that we should investigate.

**Comment by premun** [comment]
Right, then I can re-package these apps and get rid of this problem. This app hasn't been zipped by the Arcade SDK but by me manually and put to a storage for our integration tests here so we might be fine in Arcade actually.

So I will start using **tar.gz** and won't merge this change yet

**Review by greenEkatherine — APPROVED** [review]

**Review by mandel-macaque — APPROVED** [review]

**Comment by premun** [comment]
So the issue here is that my apps are actually already **tar.gz** wit hthe `+x` but when I create the Helix jobs from Windows, the executable information gets lost when we pack the Helix payload. So I will check this in so that we don't have issues with this cross platform scenario

**Pull request merged**
