### PR TITLE
[iOS] Bump versions to support Xcode 11.5

### PR DESCRIPTION
**Pull request by mandel-macaque**
Some small move of a line to match the template in xamarin-macions.

### CODE REVIEW

**Comment by mandel-macaque** [comment]
Important, the new xcode will give problems if the OS is not the correct one:

```
This Xcode version requires macOS ≥ 10.15.2 (currently running on 10.15.1)
```

**Comment by premun** [comment]
@mandel-macaque should this also update to a newer mlaunch or there is not a new one needed?

**Comment by premun** [comment]
@mandel-macaque I will be installing Xcode 11.5 on our machines tomorrow

**Comment by premun** [comment]
@mandel-macaque can you please change 
https://github.com/dotnet/xharness/blob/8f6cc04f53cb6759758ffc97c9c8ca3ab4802f7f/azure-pipelines.yml#L213
to
`https://helix.int-dot.net/`

and

https://github.com/dotnet/xharness/blob/8f6cc04f53cb6759758ffc97c9c8ca3ab4802f7f/azure-pipelines.yml#L219
to
`osx.1015.amd64.ios.open`
?

This will send the E2E tests in this PR to the staging machines I have already updated with 11.5 so we can validate before I roll everything out to production

**Comment by premun** [comment]
@mandel-macaque I couldn't push in your fork so I opened a [new PR](https://github.com/dotnet/xharness/pull/233)

**Pull request closed without merging**
