### PR TITLE
[iOS] Adjust installing simulators according to recent Xcode14 changes

### PR DESCRIPTION
**Pull request by rmarinho**
Porting https://github.com/xamarin/xamarin-macios/pull/15449/

Fixes https://github.com/dotnet/xharness/issues/923

### CODE REVIEW

**Comment by akoeplinger** [comment]
I assume we need https://github.com/dotnet/xharness/pull/955 first?

**Comment by rmarinho** [comment]
xharness is actually working fine for iOS16 for us

**Review by mandel-macaque — APPROVED** [review]

**Comment by akoeplinger** [comment]
Looks like there is a bug with an analyzer triggered by the local function, moving it out into a regular function fixes it, will file a bug.

**Comment by rmarinho** [comment]
@akoeplinger  spaces??? :D

**Pull request merged**
