### PR TITLE
Remove conflicting `-d` option (WASM and diagnostics)

### LINKED ISSUE #705: Conflicting -d argument
The `-d=` argument is used for two different things:

* https://github.com/dotnet/xharness/blob/main/src/Microsoft.DotNet.XHarness.CLI/CommandArguments/WASM/Arguments/DebuggerPortArgument.cs#L12 `DebuggerPortArgument` for wasm
* https://github.com/dotnet/xharness/commit/c8c452d7746015847956618cf0c56f931ed8647a#diff-06c7501a9453707b37cdd47ce0d256dcc409ea6bda442fd48d8aa9ded4e95068 `DiagnosticsArgument` in general (but targeted for Apple and Android)

This results in initializations problems for WASM test runs:

```
+ ./RunTests.sh
XHarness command issued: wasm test-browser --app=. --output-directory=/datadisks/disk1/work/A75F0978/w/A089091A/uploads/xharness-output --engine=V8 --engine-arg=--stack-trace-limit=1000 --js-file=runtime.js -- --run WasmTestRunner.dll Microsoft.Extensions.Configuration.CommandLine.Tests.dll -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: d
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Mono.Options.OptionSet.AddImpl(Option option)
   at Mono.Options.OptionSet.InsertItem(Int32 index, Option item)
   at System.Collections.ObjectModel.Collection`1.Add(T item)
   at Mono.Options.OptionSet.Add(String prototype, String description, Action`1 action, Boolean hidden)
   at Microsoft.DotNet.XHarness.CLI.Commands.XHarnessCommand`1.Invoke(IEnumerable`1 arguments) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/XHarnessCommand.cs:line 76
   at Mono.Options.CommandSet.Run(IEnumerable`1 arguments)
   at Microsoft.DotNet.XHarness.CLI.Program.Main(String[] args) in /_/src/Microsoft.DotNet.XHarness.CLI/Program.cs:line 49
./RunTests.sh: line 29:  8715 Aborted                 (core dumped) $HARNESS_RUNNER wasm $XHARNESS_COMMAND --app=. --output-directory=$XHARNESS_OUT --engine=V8 --engine-arg=--stack-trace-limit=1000 --js-file=runtime.js $WasmXHarnessArgs -- $WasmXHarnessMonoArgs --run WasmTestRunner.dll Microsoft.Extensions.Configuration.CommandLine.Tests.dll $WasmTestAppArgs -notrait category=IgnoreForCI -notrait category=OuterLoop -notrait category=failing $RSP_FILE
```

### PR DESCRIPTION
**Pull request by premun**
Resolves #705

### CODE REVIEW

**Comment by premun** [comment]
@radical https://github.com/dotnet/xharness/pull/706 😁

Diagnostics one is brand new so let's kill it

**Review by lambdageek — APPROVED** [review]

**Review by radical — APPROVED** [review]

**Comment by radical** [comment]
Would it make sense to add a test that just invokes all the commands with no arguments, and just expects to see "help"?

**Comment by premun** [comment]
@radical yes, that would be good, I will add that. We have 100% coverage for all Apple/Android commands in E2E tests but WASM only has one simple and very old test. But this would have value for sure.

**Comment by premun** [comment]
Issue here: https://github.com/dotnet/xharness/issues/708

**Pull request merged**
