### PR TITLE
[wasm][test-browser] Add `--browser-path` to use custom browser paths

### PR DESCRIPTION
**Pull request by radical**

### CODE REVIEW

**Review by kg — APPROVED** [review]

**Comment by radical** [comment]
I don't have permissions to merge this.

**Review by lewing — APPROVED** [review]
LGTM

**Comment by lewing** [comment]
@premun @akoeplinger 

can someone with review privileges review this?

**Comment by lewing** [comment]
cc @dotnet/xharness

**Review by premun — APPROVED** [review]

**Pull request merged**
