### PR TITLE
Remove separate CodeQL pipeline

### PR DESCRIPTION
**Pull request by akoeplinger**
CodeQL runs in the main pipeline via 1ESPT now and can't be disabled so having a separate pipeline doesn't make sense.

### CODE REVIEW

**Review by ivanpovazan — APPROVED** [review]
Just to clarify, this is basically just a clean up as we didn't run it anyway?

**Comment by akoeplinger** [comment]
We do run it (that's why I noticed) but it's pointless :D

**Comment by ivanpovazan** [comment]
You mean this one: https://dev.azure.com/dnceng/internal/_build?definitionId=1184

**Comment by akoeplinger** [comment]
Yes. I'll ask dnceng to delete it once this is merged.

**Pull request merged**
