### PR TITLE
Fix downloading of large files when installing Simulators

### LINKED ISSUE #631: Simulator installation fails to download the `.dmg`
```
info: Downloading 'https://devimages-cdn.apple.com/downloads/xcode/simulators/com.apple.pkg.iPhoneSimulatorSDK14_4-14.4.1.1611903691.dmg' to '/var/folders/8d/4hjmcr2x34dcmjft1gp7vjfr0000gn/T/simulator-installer/com.apple.pkg.iPhoneSimulatorSDK14_4-14.4.1.1611903691.dmg' (size: 5000672618 bytes = 4,769.01 MB)...

fail: Failed to install 'iOS 14.4 Simulator':
    System.Net.Http.HttpRequestException: Cannot write more bytes to the buffer than the configured maximum buffer size: 2147483647.
        at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken) in System.Net.Http.dll:token 0x6000280+0x17f
        at Microsoft.DotNet.XHarness.CLI.Commands.Apple.Simulators.InstallCommand.Install(Simulator simulator) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/InstallCommand.cs:line 149
        at Microsoft.DotNet.XHarness.CLI.Commands.Apple.Simulators.InstallCommand.InvokeInternal(ILogger logger) in /_/src/Microsoft.DotNet.XHarness.CLI/Commands/Apple/Simulators/InstallCommand.cs:line 101
dbug: Skipping 'com.apple.pkg.AppleTVSimulatorSDK14_4'

XHarness exit code: 71 (GENERAL_FAILURE)
```

We probably need retries? Or download large files like this more cautiously?

### PR DESCRIPTION
**Pull request by premun**
Also show progress and allow to turn it off via `--hide-progress`

Fixes #631

### CODE REVIEW

**Comment by premun** [comment]
@mandel-macaque if you see failures in simulator installation in `xamarin-macios`, it has the same problem as this code because this code is copied from `SimulatorInstaller` and it is downloading the `.dmg` to memory and overflowing the buffer. So you could copy this fix over.

**Review by greenEkatherine — APPROVED** [review]

**Pull request merged**
